namespace GameCheatsManager.WinUI.Services;

public sealed class LocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> _translations = new(StringComparer.Ordinal)
    {
        ["Game Cheats Manager"] = new() { ["zh_CN"] = "游戏修改器管理器", ["zh_TW"] = "遊戲修改器管理器", ["de_DE"] = "Game Cheats Manager" },
        ["Options"] = new() { ["zh_CN"] = "选项", ["zh_TW"] = "選項", ["de_DE"] = "Optionen" },
        ["Settings"] = new() { ["zh_CN"] = "设置", ["zh_TW"] = "設定", ["de_DE"] = "Einstellungen" },
        ["Import Trainers"] = new() { ["zh_CN"] = "导入修改器", ["zh_TW"] = "匯入修改器", ["de_DE"] = "Trainer importieren" },
        ["Open Trainer Download Path"] = new() { ["zh_CN"] = "打开修改器下载路径", ["zh_TW"] = "開啟修改器下載路徑", ["de_DE"] = "Trainer-Ordner öffnen" },
        ["Add Paths to Whitelist"] = new() { ["zh_CN"] = "添加路径到白名单", ["zh_TW"] = "新增路徑到白名單", ["de_DE"] = "Pfade zur Whitelist hinzufügen" },
        ["About"] = new() { ["zh_CN"] = "关于", ["zh_TW"] = "關於", ["de_DE"] = "Info" },
        ["Data Update"] = new() { ["zh_CN"] = "数据更新", ["zh_TW"] = "資料更新", ["de_DE"] = "Daten aktualisieren" },
        ["Update Translation Data"] = new() { ["zh_CN"] = "更新翻译数据", ["zh_TW"] = "更新翻譯資料", ["de_DE"] = "Übersetzungsdaten aktualisieren" },
        ["Update Trainer Search Data"] = new() { ["zh_CN"] = "更新搜索数据", ["zh_TW"] = "更新搜尋資料", ["de_DE"] = "Suchdaten aktualisieren" },
        ["Update Trainers"] = new() { ["zh_CN"] = "更新修改器", ["zh_TW"] = "更新修改器", ["de_DE"] = "Trainer aktualisieren" },
        ["Trainer Management"] = new() { ["zh_CN"] = "修改器管理", ["zh_TW"] = "修改器管理", ["de_DE"] = "Trainer-Verwaltung" },
        ["Open Trainer Management"] = new() { ["zh_CN"] = "打开修改器管理", ["zh_TW"] = "開啟修改器管理", ["de_DE"] = "Trainer-Verwaltung öffnen" },
        ["Upload Trainer"] = new() { ["zh_CN"] = "上传修改器", ["zh_TW"] = "上傳修改器", ["de_DE"] = "Trainer hochladen" },
        ["Open Upload Trainer"] = new() { ["zh_CN"] = "打开上传界面", ["zh_TW"] = "開啟上傳介面", ["de_DE"] = "Upload öffnen" },
        ["Browse All Trainers"] = new() { ["zh_CN"] = "浏览全部修改器", ["zh_TW"] = "瀏覽全部修改器", ["de_DE"] = "Alle Trainer durchsuchen" },
        ["Open Trainers Page"] = new() { ["zh_CN"] = "打开修改器页面", ["zh_TW"] = "開啟修改器頁面", ["de_DE"] = "Trainer-Seite öffnen" },
        ["Installed Trainers"] = new() { ["zh_CN"] = "已安装修改器", ["zh_TW"] = "已安裝修改器", ["de_DE"] = "Installierte Trainer" },
        ["Search for installed trainers"] = new() { ["zh_CN"] = "搜索已安装的修改器", ["zh_TW"] = "搜尋已安裝的修改器", ["de_DE"] = "Installierte Trainer suchen" },
        ["Launch"] = new() { ["zh_CN"] = "启动", ["zh_TW"] = "啟動", ["de_DE"] = "Starten" },
        ["Delete"] = new() { ["zh_CN"] = "删除", ["zh_TW"] = "刪除", ["de_DE"] = "Löschen" },
        ["Download Trainers"] = new() { ["zh_CN"] = "下载修改器", ["zh_TW"] = "下載修改器", ["de_DE"] = "Trainer herunterladen" },
        ["Enter keywords to download trainers"] = new() { ["zh_CN"] = "输入关键字下载修改器", ["zh_TW"] = "輸入關鍵字下載修改器", ["de_DE"] = "Suchbegriff zum Herunterladen eingeben" },
        ["Search"] = new() { ["zh_CN"] = "搜索", ["zh_TW"] = "搜尋", ["de_DE"] = "Suchen" },
        ["Idle"] = new() { ["zh_CN"] = "空闲", ["zh_TW"] = "閒置", ["de_DE"] = "Leerlauf" },
        ["Trainer download path:"] = new() { ["zh_CN"] = "修改器下载路径：", ["zh_TW"] = "修改器下載路徑：", ["de_DE"] = "Trainer-Speicherort:" },
        ["Browse"] = new() { ["zh_CN"] = "浏览", ["zh_TW"] = "瀏覽", ["de_DE"] = "Durchsuchen" },
        ["Activity"] = new() { ["zh_CN"] = "活动", ["zh_TW"] = "活動", ["de_DE"] = "Aktivität" },
        ["Warning"] = new() { ["zh_CN"] = "警告", ["zh_TW"] = "警告", ["de_DE"] = "Warnung" },
        ["This software is open source and provided free of charge. Resale is strictly prohibited."] = new() { ["zh_CN"] = "本软件开源且免费提供，严禁转售。", ["zh_TW"] = "本軟體開源且免費提供，嚴禁轉售。", ["de_DE"] = "Diese Software ist Open Source und kostenlos. Weiterverkauf ist verboten." },
        ["Don't show again"] = new() { ["zh_CN"] = "不再显示", ["zh_TW"] = "不再顯示", ["de_DE"] = "Nicht erneut anzeigen" },
        ["Announcement"] = new() { ["zh_CN"] = "公告", ["zh_TW"] = "公告", ["de_DE"] = "Ankündigung" },
        ["Theme"] = new() { ["zh_CN"] = "主题", ["zh_TW"] = "主題", ["de_DE"] = "Design" },
        ["Language"] = new() { ["zh_CN"] = "语言", ["zh_TW"] = "語言", ["de_DE"] = "Sprache" },
        ["Launch app on system startup"] = new() { ["zh_CN"] = "系统启动时自动运行", ["zh_TW"] = "系統啟動時自動執行", ["de_DE"] = "Beim Systemstart ausführen" },
        ["Check for software updates at startup"] = new() { ["zh_CN"] = "启动时检查软件更新", ["zh_TW"] = "啟動時檢查軟體更新", ["de_DE"] = "Beim Start nach Updates suchen" },
        ["Use safe launch path"] = new() { ["zh_CN"] = "使用安全启动路径", ["zh_TW"] = "使用安全啟動路徑", ["de_DE"] = "Sicheren Startpfad verwenden" },
        ["Always show search results in English"] = new() { ["zh_CN"] = "搜索结果始终显示英文", ["zh_TW"] = "搜尋結果始終顯示英文", ["de_DE"] = "Suchergebnisse immer auf Englisch anzeigen" },
        ["Sort search results by origin"] = new() { ["zh_CN"] = "按来源排序搜索结果", ["zh_TW"] = "按來源排序搜尋結果", ["de_DE"] = "Suchergebnisse nach Quelle sortieren" },
        ["Update trainer translations automatically"] = new() { ["zh_CN"] = "自动更新修改器翻译数据", ["zh_TW"] = "自動更新修改器翻譯資料", ["de_DE"] = "Trainer-Übersetzungen automatisch aktualisieren" },
        ["Apply"] = new() { ["zh_CN"] = "应用", ["zh_TW"] = "套用", ["de_DE"] = "Übernehmen" },
        ["Cancel"] = new() { ["zh_CN"] = "取消", ["zh_TW"] = "取消", ["de_DE"] = "Abbrechen" },
        ["Settings saved."] = new() { ["zh_CN"] = "设置已保存。", ["zh_TW"] = "設定已儲存。", ["de_DE"] = "Einstellungen gespeichert." },
        ["Theme and language changes are saved. Restart the app to fully apply them."] = new() { ["zh_CN"] = "主题和语言设置已保存，重启应用后可完全生效。", ["zh_TW"] = "主題與語言設定已儲存，重新啟動後可完全生效。", ["de_DE"] = "Design- und Spracheinstellungen wurden gespeichert. Bitte neu starten." },
        ["Current version:"] = new() { ["zh_CN"] = "当前版本：", ["zh_TW"] = "目前版本：", ["de_DE"] = "Aktuelle Version:" },
        ["Newest version:"] = new() { ["zh_CN"] = "最新版本：", ["zh_TW"] = "最新版本：", ["de_DE"] = "Neueste Version:" },
        ["Unavailable"] = new() { ["zh_CN"] = "不可用", ["zh_TW"] = "不可用", ["de_DE"] = "Nicht verfügbar" },
        ["Cheat Engine Required"] = new() { ["zh_CN"] = "需要 Cheat Engine", ["zh_TW"] = "需要 Cheat Engine", ["de_DE"] = "Cheat Engine erforderlich" },
        [".ct/.cetrainer files require Cheat Engine to run. Please install Cheat Engine and open these files with it."] = new() { ["zh_CN"] = ".ct/.cetrainer 文件需要使用 Cheat Engine 打开，请先安装 Cheat Engine。", ["zh_TW"] = ".ct/.cetrainer 檔案需要使用 Cheat Engine 開啟，請先安裝 Cheat Engine。", ["de_DE"] = ".ct/.cetrainer-Dateien benötigen Cheat Engine." },
        ["Delete Trainer"] = new() { ["zh_CN"] = "删除修改器", ["zh_TW"] = "刪除修改器", ["de_DE"] = "Trainer löschen" },
        ["Delete Original Trainers"] = new() { ["zh_CN"] = "删除原始修改器", ["zh_TW"] = "刪除原始修改器", ["de_DE"] = "Originaldateien löschen" },
        ["Do you want to delete the original trainer files?"] = new() { ["zh_CN"] = "是否删除原始修改器文件？", ["zh_TW"] = "是否刪除原始修改器檔案？", ["de_DE"] = "Originaldateien löschen?" },
        ["Keep"] = new() { ["zh_CN"] = "保留", ["zh_TW"] = "保留", ["de_DE"] = "Behalten" },
        ["Path"] = new() { ["zh_CN"] = "路径", ["zh_TW"] = "路徑", ["de_DE"] = "Pfad" },
        ["Please choose a new path."] = new() { ["zh_CN"] = "请选择一个新路径。", ["zh_TW"] = "請選擇新的路徑。", ["de_DE"] = "Bitte einen neuen Pfad wählen." },
        ["Migration complete."] = new() { ["zh_CN"] = "迁移完成。", ["zh_TW"] = "遷移完成。", ["de_DE"] = "Migration abgeschlossen." },
        ["Import"] = new() { ["zh_CN"] = "导入", ["zh_TW"] = "匯入", ["de_DE"] = "Import" },
        ["Trainer import complete."] = new() { ["zh_CN"] = "修改器导入完成。", ["zh_TW"] = "修改器匯入完成。", ["de_DE"] = "Trainer importiert." },
        ["Administrator Access Required"] = new() { ["zh_CN"] = "需要管理员权限", ["zh_TW"] = "需要管理員權限", ["de_DE"] = "Administratorrechte erforderlich" },
        ["Adding paths to the Windows Defender whitelist requires administrator rights. Continue?"] = new() { ["zh_CN"] = "将路径加入 Windows Defender 白名单需要管理员权限，是否继续？", ["zh_TW"] = "將路徑加入 Windows Defender 白名單需要管理員權限，是否繼續？", ["de_DE"] = "Administratorrechte zum Whitelisten erforderlich. Fortfahren?" },
        ["Continue"] = new() { ["zh_CN"] = "继续", ["zh_TW"] = "繼續", ["de_DE"] = "Fortfahren" },
        ["Whitelist"] = new() { ["zh_CN"] = "白名单", ["zh_TW"] = "白名單", ["de_DE"] = "Whitelist" },
        ["Paths added to Windows Defender whitelist."] = new() { ["zh_CN"] = "路径已加入 Windows Defender 白名单。", ["zh_TW"] = "路徑已加入 Windows Defender 白名單。", ["de_DE"] = "Pfade wurden hinzugefügt." },
        ["Failed to add paths to whitelist."] = new() { ["zh_CN"] = "添加白名单失败。", ["zh_TW"] = "加入白名單失敗。", ["de_DE"] = "Whitelist konnte nicht aktualisiert werden." },
        ["Translation Data"] = new() { ["zh_CN"] = "翻译数据", ["zh_TW"] = "翻譯資料", ["de_DE"] = "Übersetzungsdaten" },
        ["Translation data updated."] = new() { ["zh_CN"] = "翻译数据已更新。", ["zh_TW"] = "翻譯資料已更新。", ["de_DE"] = "Übersetzungsdaten aktualisiert." },
        ["Translation data update failed."] = new() { ["zh_CN"] = "翻译数据更新失败。", ["zh_TW"] = "翻譯資料更新失敗。", ["de_DE"] = "Übersetzungsdaten konnten nicht aktualisiert werden." },
        ["Search Data"] = new() { ["zh_CN"] = "搜索数据", ["zh_TW"] = "搜尋資料", ["de_DE"] = "Suchdaten" },
        ["Trainer search data updated."] = new() { ["zh_CN"] = "修改器搜索数据已更新。", ["zh_TW"] = "修改器搜尋資料已更新。", ["de_DE"] = "Suchdaten aktualisiert." },
        ["One or more data sources failed to update."] = new() { ["zh_CN"] = "一个或多个数据源更新失败。", ["zh_TW"] = "一個或多個資料來源更新失敗。", ["de_DE"] = "Mindestens eine Quelle konnte nicht aktualisiert werden." },
        ["Updates"] = new() { ["zh_CN"] = "更新", ["zh_TW"] = "更新", ["de_DE"] = "Updates" },
        ["No trainer updates found."] = new() { ["zh_CN"] = "未发现修改器更新。", ["zh_TW"] = "未發現修改器更新。", ["de_DE"] = "Keine Trainer-Updates gefunden." },
        ["Update Available"] = new() { ["zh_CN"] = "发现更新", ["zh_TW"] = "發現更新", ["de_DE"] = "Update verfügbar" },
        ["Open"] = new() { ["zh_CN"] = "打开", ["zh_TW"] = "開啟", ["de_DE"] = "Öffnen" },
        ["Later"] = new() { ["zh_CN"] = "稍后", ["zh_TW"] = "稍後", ["de_DE"] = "Später" },
        ["Download"] = new() { ["zh_CN"] = "下载", ["zh_TW"] = "下載", ["de_DE"] = "Download" },
        ["Download Failed"] = new() { ["zh_CN"] = "下载失败", ["zh_TW"] = "下載失敗", ["de_DE"] = "Download fehlgeschlagen" },
        ["Delete Failed"] = new() { ["zh_CN"] = "删除失败", ["zh_TW"] = "刪除失敗", ["de_DE"] = "Löschen fehlgeschlagen" },
        ["Backend config detected: signed download available."] = new() { ["zh_CN"] = "已检测到后端配置：签名下载可用。", ["zh_TW"] = "已偵測到後端設定：簽名下載可用。", ["de_DE"] = "Backend-Konfiguration erkannt: Signierte Downloads verfügbar." },
        ["Backend config detected: signed download missing."] = new() { ["zh_CN"] = "未检测到后端配置：签名下载不可用。", ["zh_TW"] = "未偵測到後端設定：簽名下載不可用。", ["de_DE"] = "Backend-Konfiguration fehlt: Signierte Downloads nicht verfügbar." },
        ["Private backend is not configured. Switched FLiNG to official mode; GCM/XiaoXing/CT signed downloads are unavailable."] = new() { ["zh_CN"] = "未配置私有后端，已自动切换到 FLiNG 官方模式；GCM/XiaoXing/CT 的签名下载不可用。", ["zh_TW"] = "未設定私有後端，已自動切換到 FLiNG 官方模式；GCM/XiaoXing/CT 的簽名下載不可用。", ["de_DE"] = "Privates Backend nicht konfiguriert. FLiNG wurde auf offiziellen Modus umgestellt." },
        ["This source requires the private Game-Zone backend configuration, which is not present in this workspace."] = new() { ["zh_CN"] = "该来源依赖私有 Game-Zone 后端配置，当前工作区中不存在该配置。", ["zh_TW"] = "此來源依賴私有 Game-Zone 後端設定，目前工作區中不存在該設定。", ["de_DE"] = "Diese Quelle benötigt die private Game-Zone-Backend-Konfiguration." }
    };

    private readonly Dictionary<string, Dictionary<string, string>> _extraTranslations = new(StringComparer.Ordinal)
    {
        ["Close"] = new() { ["zh_CN"] = "关闭", ["zh_TW"] = "關閉", ["de_DE"] = "Close" },
        ["Save"] = new() { ["zh_CN"] = "保存", ["zh_TW"] = "儲存", ["de_DE"] = "Save" },
        ["OK"] = new() { ["zh_CN"] = "确定", ["zh_TW"] = "確定", ["de_DE"] = "OK" },
        ["Upload"] = new() { ["zh_CN"] = "上传", ["zh_TW"] = "上傳", ["de_DE"] = "Upload" },
        ["Search Failed"] = new() { ["zh_CN"] = "搜索失败", ["zh_TW"] = "搜尋失敗", ["de_DE"] = "Search Failed" },
        ["No search results found."] = new() { ["zh_CN"] = "没有找到搜索结果。", ["zh_TW"] = "沒有找到搜尋結果。", ["de_DE"] = "No search results found." },
        ["Search returned {0} trainer(s)."] = new() { ["zh_CN"] = "搜索返回了 {0} 个修改器。", ["zh_TW"] = "搜尋返回了 {0} 個修改器。", ["de_DE"] = "Search returned {0} trainer(s)." },
        ["Search failed: {0}"] = new() { ["zh_CN"] = "搜索失败：{0}", ["zh_TW"] = "搜尋失敗：{0}", ["de_DE"] = "Search failed: {0}" },
        ["Updating {0}..."] = new() { ["zh_CN"] = "正在更新 {0}...", ["zh_TW"] = "正在更新 {0}...", ["de_DE"] = "Updating {0}..." },
        ["Updating translation data..."] = new() { ["zh_CN"] = "正在更新翻译数据...", ["zh_TW"] = "正在更新翻譯資料...", ["de_DE"] = "Updating translation data..." },
        ["Updating GCM data..."] = new() { ["zh_CN"] = "正在更新 GCM 数据...", ["zh_TW"] = "正在更新 GCM 資料...", ["de_DE"] = "Updating GCM data..." },
        ["GCM data updated."] = new() { ["zh_CN"] = "GCM 数据已更新。", ["zh_TW"] = "GCM 資料已更新。", ["de_DE"] = "GCM data updated." },
        ["GCM data update failed."] = new() { ["zh_CN"] = "GCM 数据更新失败。", ["zh_TW"] = "GCM 資料更新失敗。", ["de_DE"] = "GCM data update failed." },
        ["Updating FLiNG data..."] = new() { ["zh_CN"] = "正在更新 FLiNG 数据...", ["zh_TW"] = "正在更新 FLiNG 資料...", ["de_DE"] = "Updating FLiNG data..." },
        ["FLiNG data updated."] = new() { ["zh_CN"] = "FLiNG 数据已更新。", ["zh_TW"] = "FLiNG 資料已更新。", ["de_DE"] = "FLiNG data updated." },
        ["FLiNG data update failed."] = new() { ["zh_CN"] = "FLiNG 数据更新失败。", ["zh_TW"] = "FLiNG 資料更新失敗。", ["de_DE"] = "FLiNG data update failed." },
        ["Updating XiaoXing data..."] = new() { ["zh_CN"] = "正在更新小幸数据...", ["zh_TW"] = "正在更新小幸資料...", ["de_DE"] = "Updating XiaoXing data..." },
        ["XiaoXing data updated."] = new() { ["zh_CN"] = "小幸数据已更新。", ["zh_TW"] = "小幸資料已更新。", ["de_DE"] = "XiaoXing data updated." },
        ["XiaoXing data update failed."] = new() { ["zh_CN"] = "小幸数据更新失败。", ["zh_TW"] = "小幸資料更新失敗。", ["de_DE"] = "XiaoXing data update failed." },
        ["Updating Cheat Table data..."] = new() { ["zh_CN"] = "正在更新 Cheat Table 数据...", ["zh_TW"] = "正在更新 Cheat Table 資料...", ["de_DE"] = "Updating Cheat Table data..." },
        ["Cheat Table data updated."] = new() { ["zh_CN"] = "Cheat Table 数据已更新。", ["zh_TW"] = "Cheat Table 資料已更新。", ["de_DE"] = "Cheat Table data updated." },
        ["Cheat Table data update failed."] = new() { ["zh_CN"] = "Cheat Table 数据更新失败。", ["zh_TW"] = "Cheat Table 資料更新失敗。", ["de_DE"] = "Cheat Table data update failed." },
        ["Checking for trainer updates..."] = new() { ["zh_CN"] = "正在检查修改器更新...", ["zh_TW"] = "正在檢查修改器更新...", ["de_DE"] = "Checking for trainer updates..." },
        ["Found {0} trainer update(s)."] = new() { ["zh_CN"] = "发现 {0} 个修改器更新。", ["zh_TW"] = "發現 {0} 個修改器更新。", ["de_DE"] = "Found {0} trainer update(s)." },
        ["New version found: {0} -> {1}\n\nOpen the release page now?"] = new() { ["zh_CN"] = "发现新版本：{0} -> {1}\n\n现在打开发布页面吗？", ["zh_TW"] = "發現新版本：{0} -> {1}\n\n現在開啟發布頁面嗎？", ["de_DE"] = "New version found: {0} -> {1}\n\nOpen the release page now?" },
        ["App update check failed: {0}"] = new() { ["zh_CN"] = "应用更新检查失败：{0}", ["zh_TW"] = "應用更新檢查失敗：{0}", ["de_DE"] = "App update check failed: {0}" },
        ["Announcement fetch failed: {0}"] = new() { ["zh_CN"] = "获取公告失败：{0}", ["zh_TW"] = "取得公告失敗：{0}", ["de_DE"] = "Announcement fetch failed: {0}" },
        ["Enable search for GCM and Other trainers"] = new() { ["zh_CN"] = "启用 GCM 和其他修改器搜索", ["zh_TW"] = "啟用 GCM 和其他修改器搜尋", ["de_DE"] = "Enable search for GCM and Other trainers" },
        ["Update GCM data automatically"] = new() { ["zh_CN"] = "自动更新 GCM 数据", ["zh_TW"] = "自動更新 GCM 資料", ["de_DE"] = "Update GCM data automatically" },
        ["Update GCM trainers automatically"] = new() { ["zh_CN"] = "自动更新 GCM 修改器", ["zh_TW"] = "自動更新 GCM 修改器", ["de_DE"] = "Update GCM trainers automatically" },
        ["Download server"] = new() { ["zh_CN"] = "下载服务器", ["zh_TW"] = "下載伺服器", ["de_DE"] = "Download server" },
        ["Remove trainer background music"] = new() { ["zh_CN"] = "移除修改器背景音乐", ["zh_TW"] = "移除修改器背景音樂", ["de_DE"] = "Remove trainer background music" },
        ["Update FLiNG data automatically"] = new() { ["zh_CN"] = "自动更新 FLiNG 数据", ["zh_TW"] = "自動更新 FLiNG 資料", ["de_DE"] = "Update FLiNG data automatically" },
        ["Update FLiNG trainers automatically"] = new() { ["zh_CN"] = "自动更新 FLiNG 修改器", ["zh_TW"] = "自動更新 FLiNG 修改器", ["de_DE"] = "Update FLiNG trainers automatically" },
        ["Enable search for XiaoXing trainers"] = new() { ["zh_CN"] = "启用小幸修改器搜索", ["zh_TW"] = "啟用小幸修改器搜尋", ["de_DE"] = "Enable search for XiaoXing trainers" },
        ["Unlock all XiaoXing functions"] = new() { ["zh_CN"] = "解锁全部小幸功能", ["zh_TW"] = "解鎖全部小幸功能", ["de_DE"] = "Unlock all XiaoXing functions" },
        ["Update XiaoXing data automatically"] = new() { ["zh_CN"] = "自动更新小幸数据", ["zh_TW"] = "自動更新小幸資料", ["de_DE"] = "Update XiaoXing data automatically" },
        ["Update XiaoXing trainers automatically"] = new() { ["zh_CN"] = "自动更新小幸修改器", ["zh_TW"] = "自動更新小幸修改器", ["de_DE"] = "Update XiaoXing trainers automatically" },
        ["Cheat Engine is installed."] = new() { ["zh_CN"] = "已安装 Cheat Engine。", ["zh_TW"] = "已安裝 Cheat Engine。", ["de_DE"] = "Cheat Engine is installed." },
        ["Please select a valid Cheat Engine installation path."] = new() { ["zh_CN"] = "请选择有效的 Cheat Engine 安装路径。", ["zh_TW"] = "請選擇有效的 Cheat Engine 安裝路徑。", ["de_DE"] = "Please select a valid Cheat Engine installation path." },
        ["Add Simplified Chinese"] = new() { ["zh_CN"] = "添加简体中文", ["zh_TW"] = "加入簡體中文", ["de_DE"] = "Add Simplified Chinese" },
        ["Enable search for Cheat Tables"] = new() { ["zh_CN"] = "启用 Cheat Tables 搜索", ["zh_TW"] = "啟用 Cheat Tables 搜尋", ["de_DE"] = "Enable search for Cheat Tables" },
        ["Update Cheat Table data automatically"] = new() { ["zh_CN"] = "自动更新 Cheat Table 数据", ["zh_TW"] = "自動更新 Cheat Table 資料", ["de_DE"] = "Update Cheat Table data automatically" },
        ["Update Cheat Table trainers automatically"] = new() { ["zh_CN"] = "自动更新 Cheat Table 修改器", ["zh_TW"] = "自動更新 Cheat Table 修改器", ["de_DE"] = "Update Cheat Table trainers automatically" },
        ["Wand not installed"] = new() { ["zh_CN"] = "未安装 Wand", ["zh_TW"] = "未安裝 Wand", ["de_DE"] = "Wand not installed" },
        ["Activate Wand Pro"] = new() { ["zh_CN"] = "启用 Wand Pro", ["zh_TW"] = "啟用 Wand Pro", ["de_DE"] = "Activate Wand Pro" },
        ["Disable Wand Auto Update"] = new() { ["zh_CN"] = "禁用 Wand 自动更新", ["zh_TW"] = "停用 Wand 自動更新", ["de_DE"] = "Disable Wand Auto Update" },
        ["Delete All Other Wand Versions"] = new() { ["zh_CN"] = "删除其他所有 Wand 版本", ["zh_TW"] = "刪除其他所有 Wand 版本", ["de_DE"] = "Delete All Other Wand Versions" },
        ["Apply Cheat Engine Changes"] = new() { ["zh_CN"] = "应用 Cheat Engine 修改", ["zh_TW"] = "套用 Cheat Engine 修改", ["de_DE"] = "Apply Cheat Engine Changes" },
        ["Successfully added translation files."] = new() { ["zh_CN"] = "已成功添加翻译文件。", ["zh_TW"] = "已成功加入翻譯檔案。", ["de_DE"] = "Successfully added translation files." },
        ["Failed to add translation files."] = new() { ["zh_CN"] = "添加翻译文件失败。", ["zh_TW"] = "加入翻譯檔案失敗。", ["de_DE"] = "Failed to add translation files." },
        ["Apply Wand Changes"] = new() { ["zh_CN"] = "应用 Wand 修改", ["zh_TW"] = "套用 Wand 修改", ["de_DE"] = "Apply Wand Changes" },
        ["Apply Cheat Evolution Changes"] = new() { ["zh_CN"] = "应用 Cheat Evolution 修改", ["zh_TW"] = "套用 Cheat Evolution 修改", ["de_DE"] = "Apply Cheat Evolution Changes" },
        ["Patch successful."] = new() { ["zh_CN"] = "补丁应用成功。", ["zh_TW"] = "修補成功。", ["de_DE"] = "Patch successful." },
        ["Patch failed."] = new() { ["zh_CN"] = "补丁应用失败。", ["zh_TW"] = "修補失敗。", ["de_DE"] = "Patch failed." },
        ["Selected Wand version was not found."] = new() { ["zh_CN"] = "未找到所选 Wand 版本。", ["zh_TW"] = "未找到所選 Wand 版本。", ["de_DE"] = "Selected Wand version was not found." },
        ["Wand is currently running. Close it before applying patches."] = new() { ["zh_CN"] = "Wand 当前正在运行。请先关闭后再应用补丁。", ["zh_TW"] = "Wand 目前正在執行。請先關閉後再套用修補。", ["de_DE"] = "Wand is currently running. Close it before applying patches." },
        ["Failed to patch the Wand executable."] = new() { ["zh_CN"] = "修补 Wand 可执行文件失败。", ["zh_TW"] = "修補 Wand 可執行檔失敗。", ["de_DE"] = "Failed to patch the Wand executable." },
        ["Failed to extract Wand app resources."] = new() { ["zh_CN"] = "提取 Wand 应用资源失败。", ["zh_TW"] = "擷取 Wand 應用資源失敗。", ["de_DE"] = "Failed to extract Wand app resources." },
        ["Patch patterns endpoint is not configured."] = new() { ["zh_CN"] = "补丁规则接口未配置。", ["zh_TW"] = "修補規則端點未設定。", ["de_DE"] = "Patch patterns endpoint is not configured." },
        ["Failed to patch Wand JavaScript bundles."] = new() { ["zh_CN"] = "修补 Wand JavaScript 包失败。", ["zh_TW"] = "修補 Wand JavaScript 套件失敗。", ["de_DE"] = "Failed to patch Wand JavaScript bundles." },
        ["Failed to rebuild Wand resources."] = new() { ["zh_CN"] = "重建 Wand 资源失败。", ["zh_TW"] = "重建 Wand 資源失敗。", ["de_DE"] = "Failed to rebuild Wand resources." },
        ["Wand Pro activated."] = new() { ["zh_CN"] = "Wand Pro 已启用。", ["zh_TW"] = "Wand Pro 已啟用。", ["de_DE"] = "Wand Pro activated." },
        ["Wand Pro disabled."] = new() { ["zh_CN"] = "Wand Pro 已停用。", ["zh_TW"] = "Wand Pro 已停用。", ["de_DE"] = "Wand Pro disabled." },
        ["Wand auto update disabled."] = new() { ["zh_CN"] = "Wand 自动更新已禁用。", ["zh_TW"] = "Wand 自動更新已停用。", ["de_DE"] = "Wand auto update disabled." },
        ["Wand auto update enabled."] = new() { ["zh_CN"] = "Wand 自动更新已启用。", ["zh_TW"] = "Wand 自動更新已啟用。", ["de_DE"] = "Wand auto update enabled." },
        ["Failed to update Wand updater state: {0}"] = new() { ["zh_CN"] = "更新 Wand 更新器状态失败：{0}", ["zh_TW"] = "更新 Wand 更新器狀態失敗：{0}", ["de_DE"] = "Failed to update Wand updater state: {0}" },
        ["Deleted Wand version: {0}"] = new() { ["zh_CN"] = "已删除 Wand 版本：{0}", ["zh_TW"] = "已刪除 Wand 版本：{0}", ["de_DE"] = "Deleted Wand version: {0}" },
        ["Cheat Evolution patch file is present."] = new() { ["zh_CN"] = "已存在 Cheat Evolution 补丁文件。", ["zh_TW"] = "已存在 Cheat Evolution 修補檔案。", ["de_DE"] = "Cheat Evolution patch file is present." },
        ["Cheat Evolution is installed and ready to patch."] = new() { ["zh_CN"] = "已安装 Cheat Evolution，可进行补丁操作。", ["zh_TW"] = "已安裝 Cheat Evolution，可進行修補。", ["de_DE"] = "Cheat Evolution is installed and ready to patch." },
        ["Invalid Cheat Evolution installation path."] = new() { ["zh_CN"] = "Cheat Evolution 安装路径无效。", ["zh_TW"] = "Cheat Evolution 安裝路徑無效。", ["de_DE"] = "Invalid Cheat Evolution installation path." },
        ["Cheat Engine path"] = new() { ["zh_CN"] = "Cheat Engine 路径", ["zh_TW"] = "Cheat Engine 路徑", ["de_DE"] = "Cheat Engine path" },
        ["Wand path"] = new() { ["zh_CN"] = "Wand 路径", ["zh_TW"] = "Wand 路徑", ["de_DE"] = "Wand path" },
        ["Installed versions"] = new() { ["zh_CN"] = "已安装版本", ["zh_TW"] = "已安裝版本", ["de_DE"] = "Installed versions" },
        ["Patch method"] = new() { ["zh_CN"] = "补丁方式", ["zh_TW"] = "修補方式", ["de_DE"] = "Patch method" },
        ["Cheat Evolution path"] = new() { ["zh_CN"] = "Cheat Evolution 路径", ["zh_TW"] = "Cheat Evolution 路徑", ["de_DE"] = "Cheat Evolution path" },
        ["Trainer management settings saved."] = new() { ["zh_CN"] = "修改器管理设置已保存。", ["zh_TW"] = "修改器管理設定已儲存。", ["de_DE"] = "Trainer management settings saved." },
        ["Contact info"] = new() { ["zh_CN"] = "联系方式", ["zh_TW"] = "聯絡方式", ["de_DE"] = "Contact info" },
        ["Email (optional)"] = new() { ["zh_CN"] = "邮箱（可选）", ["zh_TW"] = "電子郵件（可選）", ["de_DE"] = "Email (optional)" },
        ["Trainer name"] = new() { ["zh_CN"] = "修改器名称", ["zh_TW"] = "修改器名稱", ["de_DE"] = "Trainer name" },
        ["Trainer source"] = new() { ["zh_CN"] = "修改器来源", ["zh_TW"] = "修改器來源", ["de_DE"] = "Trainer source" },
        ["Trainer file"] = new() { ["zh_CN"] = "修改器文件", ["zh_TW"] = "修改器檔案", ["de_DE"] = "Trainer file" },
        ["Original URL or author (optional)"] = new() { ["zh_CN"] = "原始链接或作者（可选）", ["zh_TW"] = "原始連結或作者（可選）", ["de_DE"] = "Original URL or author (optional)" },
        ["Additional notes"] = new() { ["zh_CN"] = "附加说明", ["zh_TW"] = "附加說明", ["de_DE"] = "Additional notes" },
        ["Select a trainer file"] = new() { ["zh_CN"] = "选择修改器文件", ["zh_TW"] = "選擇修改器檔案", ["de_DE"] = "Select a trainer file" },
        ["Please select a valid trainer file."] = new() { ["zh_CN"] = "请选择有效的修改器文件。", ["zh_TW"] = "請選擇有效的修改器檔案。", ["de_DE"] = "Please select a valid trainer file." },
        ["Please provide a trainer name."] = new() { ["zh_CN"] = "请输入修改器名称。", ["zh_TW"] = "請輸入修改器名稱。", ["de_DE"] = "Please provide a trainer name." },
        ["Upload backend is not configured."] = new() { ["zh_CN"] = "上传后端未配置。", ["zh_TW"] = "上傳後端未設定。", ["de_DE"] = "Upload backend is not configured." },
        ["Failed to retrieve upload URL."] = new() { ["zh_CN"] = "获取上传地址失败。", ["zh_TW"] = "取得上傳網址失敗。", ["de_DE"] = "Failed to retrieve upload URL." },
        ["Upload successful. Thank you for your contribution."] = new() { ["zh_CN"] = "上传成功。感谢你的贡献。", ["zh_TW"] = "上傳成功。感謝你的貢獻。", ["de_DE"] = "Upload successful. Thank you for your contribution." },
        ["Upload failed."] = new() { ["zh_CN"] = "上传失败。", ["zh_TW"] = "上傳失敗。", ["de_DE"] = "Upload failed." },
        ["Checking for internet connection..."] = new() { ["zh_CN"] = "正在检查网络连接...", ["zh_TW"] = "正在檢查網路連線...", ["de_DE"] = "Checking for internet connection..." },
        ["No internet connection, download failed."] = new() { ["zh_CN"] = "没有网络连接，下载失败。", ["zh_TW"] = "沒有網路連線，下載失敗。", ["de_DE"] = "No internet connection, download failed." },
        ["Downloading..."] = new() { ["zh_CN"] = "正在下载...", ["zh_TW"] = "正在下載...", ["de_DE"] = "Downloading..." },
        ["Decompressing..."] = new() { ["zh_CN"] = "正在解压...", ["zh_TW"] = "正在解壓...", ["de_DE"] = "Decompressing..." },
        ["No trainer files were prepared for installation."] = new() { ["zh_CN"] = "没有可安装的修改器文件。", ["zh_TW"] = "沒有可安裝的修改器檔案。", ["de_DE"] = "No trainer files were prepared for installation." },
        ["Download success!"] = new() { ["zh_CN"] = "下载成功！", ["zh_TW"] = "下載成功！", ["de_DE"] = "Download success!" },
        ["Failed to determine trainer download link."] = new() { ["zh_CN"] = "无法确定修改器下载链接。", ["zh_TW"] = "無法確定修改器下載連結。", ["de_DE"] = "Failed to determine trainer download link." },
        ["Internet request failed."] = new() { ["zh_CN"] = "网络请求失败。", ["zh_TW"] = "網路請求失敗。", ["de_DE"] = "Internet request failed." },
        ["Could not find the downloaded trainer file. Try disabling antivirus and retry."] = new() { ["zh_CN"] = "未找到下载后的修改器文件。请尝试暂时关闭杀毒软件后重试。", ["zh_TW"] = "未找到下載後的修改器檔案。請嘗試暫時關閉防毒軟體後重試。", ["de_DE"] = "Could not find the downloaded trainer file. Try disabling antivirus and retry." },
        ["Removing trainer background music..."] = new() { ["zh_CN"] = "正在移除修改器背景音乐...", ["zh_TW"] = "正在移除修改器背景音樂...", ["de_DE"] = "Removing trainer background music..." },
        ["Failed to retrieve signed download URL."] = new() { ["zh_CN"] = "获取签名下载链接失败。", ["zh_TW"] = "取得簽名下載連結失敗。", ["de_DE"] = "Failed to retrieve signed download URL." },
        ["Patching..."] = new() { ["zh_CN"] = "正在打补丁...", ["zh_TW"] = "正在修補...", ["de_DE"] = "Patching..." },
        ["Trainer already exists, aborted download."] = new() { ["zh_CN"] = "修改器已存在，已取消下载。", ["zh_TW"] = "修改器已存在，已取消下載。", ["de_DE"] = "Trainer already exists, aborted download." },
        ["Unsupported trainer origin: {0}"] = new() { ["zh_CN"] = "不支持的修改器来源：{0}", ["zh_TW"] = "不支援的修改器來源：{0}", ["de_DE"] = "Unsupported trainer origin: {0}" },
        ["An error occurred when moving trainer: {0}"] = new() { ["zh_CN"] = "移动修改器时发生错误：{0}", ["zh_TW"] = "移動修改器時發生錯誤：{0}", ["de_DE"] = "An error occurred when moving trainer: {0}" },
        ["An error occurred while extracting archive: {0}"] = new() { ["zh_CN"] = "解压压缩包时发生错误：{0}", ["zh_TW"] = "解壓壓縮檔時發生錯誤：{0}", ["de_DE"] = "An error occurred while extracting archive: {0}" },
        ["An error occurred while extracting downloaded trainer: {0}"] = new() { ["zh_CN"] = "解压下载的修改器时发生错误：{0}", ["zh_TW"] = "解壓下載的修改器時發生錯誤：{0}", ["de_DE"] = "An error occurred while extracting downloaded trainer: {0}" },
        ["Launching trainer..."] = new() { ["zh_CN"] = "正在启动修改器...", ["zh_TW"] = "正在啟動修改器...", ["de_DE"] = "Launching trainer..." },
        ["Failed to start the trainer."] = new() { ["zh_CN"] = "启动修改器失败。", ["zh_TW"] = "啟動修改器失敗。", ["de_DE"] = "Failed to start the trainer." },
        ["The operating system ran out of memory or resources while starting the trainer."] = new() { ["zh_CN"] = "启动修改器时，操作系统内存或资源不足。", ["zh_TW"] = "啟動修改器時，作業系統記憶體或資源不足。", ["de_DE"] = "The operating system ran out of memory or resources while starting the trainer." },
        ["The trainer file could not be found."] = new() { ["zh_CN"] = "找不到修改器文件。", ["zh_TW"] = "找不到修改器檔案。", ["de_DE"] = "The trainer file could not be found." },
        ["The trainer path could not be found."] = new() { ["zh_CN"] = "找不到修改器路径。", ["zh_TW"] = "找不到修改器路徑。", ["de_DE"] = "The trainer path could not be found." },
        ["Trainer launch was denied or canceled by UAC."] = new() { ["zh_CN"] = "修改器启动被 UAC 拒绝或取消。", ["zh_TW"] = "修改器啟動被 UAC 拒絕或取消。", ["de_DE"] = "Trainer launch was denied or canceled by UAC." },
        ["Access was denied when starting the trainer."] = new() { ["zh_CN"] = "启动修改器时被拒绝访问。", ["zh_TW"] = "啟動修改器時被拒絕存取。", ["de_DE"] = "Access was denied when starting the trainer." },
        ["The system ran out of memory while starting the trainer."] = new() { ["zh_CN"] = "启动修改器时系统内存不足。", ["zh_TW"] = "啟動修改器時系統記憶體不足。", ["de_DE"] = "The system ran out of memory while starting the trainer." },
        ["A sharing violation prevented the trainer from starting."] = new() { ["zh_CN"] = "共享冲突导致修改器无法启动。", ["zh_TW"] = "共用衝突導致修改器無法啟動。", ["de_DE"] = "A sharing violation prevented the trainer from starting." },
        ["The file association is incomplete or invalid."] = new() { ["zh_CN"] = "文件关联不完整或无效。", ["zh_TW"] = "檔案關聯不完整或無效。", ["de_DE"] = "The file association is incomplete or invalid." },
        ["The DDE operation timed out while starting the trainer."] = new() { ["zh_CN"] = "启动修改器时 DDE 操作超时。", ["zh_TW"] = "啟動修改器時 DDE 作業逾時。", ["de_DE"] = "The DDE operation timed out while starting the trainer." },
        ["The DDE operation failed while starting the trainer."] = new() { ["zh_CN"] = "启动修改器时 DDE 操作失败。", ["zh_TW"] = "啟動修改器時 DDE 作業失敗。", ["de_DE"] = "The DDE operation failed while starting the trainer." },
        ["The file association is busy."] = new() { ["zh_CN"] = "文件关联程序正忙。", ["zh_TW"] = "檔案關聯程式正忙。", ["de_DE"] = "The file association is busy." },
        ["No application is associated with this trainer file type."] = new() { ["zh_CN"] = "没有程序与此修改器文件类型关联。", ["zh_TW"] = "沒有程式與此修改器檔案類型關聯。", ["de_DE"] = "No application is associated with this trainer file type." },
        ["Failed to start the trainer with administrator privileges."] = new() { ["zh_CN"] = "无法以管理员权限启动修改器。", ["zh_TW"] = "無法以系統管理員權限啟動修改器。", ["de_DE"] = "Failed to start the trainer with administrator privileges." },
        ["Delete {0}?"] = new() { ["zh_CN"] = "删除 {0}？", ["zh_TW"] = "刪除 {0}？", ["de_DE"] = "Delete {0}?" },
        ["Trainer deleted."] = new() { ["zh_CN"] = "修改器已删除。", ["zh_TW"] = "修改器已刪除。", ["de_DE"] = "Trainer deleted." },
        ["Migrating existing trainers..."] = new() { ["zh_CN"] = "正在迁移现有修改器...", ["zh_TW"] = "正在遷移現有修改器...", ["de_DE"] = "Migrating existing trainers..." },
        ["Launch {0}"] = new() { ["zh_CN"] = "启动 {0}", ["zh_TW"] = "啟動 {0}", ["de_DE"] = "Launch {0}" }
    };

    public string Translate(string text, string language)
    {
        if (language == "en_US")
        {
            return text;
        }

        if (_extraTranslations.TryGetValue(text, out var extraMap) && extraMap.TryGetValue(language, out var extraTranslated))
        {
            return extraTranslated;
        }

        if (_translations.TryGetValue(text, out var map) && map.TryGetValue(language, out var translated))
        {
            return translated;
        }

        return text;
    }
}
